### ISSUE TITLE
Fixing Russian translation

### ISSUE THREAD

**Issue by kroopik** [MrMurdock11/neo-omni#5]
Заменить хинт «Введите команду или искать» на «Поиск в браузере»
![image](https://github.com/MrMurdock11/neo-omni/assets/52932534/d4edec19-9e00-4196-8587-8f4b182cf2f3)

**Comment by MrMurdock11** [comment]
I've changed message for Russian language. You can find my changes [here](https://github.com/MrMurdock11/neo-omni/commit/e275372e11edee97dddfb1a751227ddaf2ff9917).
