### ISSUE TITLE
Use locale from browser settings

### ISSUE THREAD

**Issue by kroopik** [MrMurdock11/neo-omni#6]
В настоящий момент локаль расширения зависит от локали веб страницы, на которой оно открыто см. скрин
![image](https://github.com/MrMurdock11/neo-omni/assets/52932534/9d77534b-3391-414b-8a9d-ef082e56cf39)
![image](https://github.com/MrMurdock11/neo-omni/assets/52932534/d0ec6d1b-caa5-4e9f-bea5-8387a524899f)

**Comment by kroopik** [comment]
Свзяано с сохранением дефолтных настроек

**Comment by MrMurdock11** [comment]
I've fixed the issue with saving default settings. You can find my changes [here](https://github.com/MrMurdock11/neo-omni/commit/2fae8aa023c1cbdcbcad6dfdf051e851c9e5e4fc).
