### ISSUE TITLE
Hide grouped tabs or tabs.

### ISSUE THREAD

**Issue by MrMurdock11** [MrMurdock11/neo-omni#8]
Is it possible to hide grouped tabs/tabs?
Example usage:
1. When I'm working on a new feature, I have a lot of content collected and I'm grouping them. I want to be able to hide them all from the tab bar, but not lose them.
2. But if I have a need for the whole group again, I could restore them.

**Comment by kungfux** [comment]
Chrome is providing this feature now out of the box

![image](https://github.com/MrMurdock11/neo-omni/assets/10548881/f4da0eff-c60c-42f5-b69d-7afc7988313a)

**Comment by MrMurdock11** [comment]
Thank you, @kungfux . I'll close this one then
